import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const buildDate = new Date();
const buildTimestamp = buildDate.toLocaleString('en-US', {
    year: 'numeric',
    month: '2-digit', 
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    timeZoneName: 'short'
});

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Built at: ${buildTimestamp}
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

console.log(`🔨 Building OneiroMetrics plugin...`);
console.log(`📅 Build timestamp: ${buildTimestamp}`);
console.log(`🏗️  Mode: ${prod ? 'production' : 'development'}`);

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
});

if (prod) {
    await context.rebuild();
    const completedAt = new Date().toLocaleString('en-US', {
        year: 'numeric',
        month: '2-digit', 
        day: '2-digit',
        hour: '2-digit',
        minute: '2-digit',
        second: '2-digit',
        timeZoneName: 'short'
    });
    console.log(`✅ Production build completed at ${completedAt}`);
    process.exit(0);
} else {
    console.log(`👀 Watching for changes...`);
    await context.watch();
} 